### ISSUE TITLE
why is there my repo in this code 

### ISSUE THREAD

**Issue by floppyflop2** [WakeCaine/socialgraphsfiles#2]
https://github.com/WakeCaine/socialgraphsfiles/blob/ce12d2254ed11cf3695e2343c93aba0479602de9/_MAIN_social_graphs/_list/835001_840000_list#L2215C1-L2215C1

why is there my repo in this code ?

**Comment by WakeCaine** [comment]
If you look in index.html. Basically your repo was one of the repos linked that were pulled by query(no code, just tag based what that repo was about) and then used to analyze connections between users and contributors. Nothing malicious, just old student project.

> Data is limited by query <i>"game"<i> (e.g. Repository for game development, the games created by users, and so on)
>                     it includes <b>around 849.000 repositories</b> that translates <b>around 5 GB data</b>. It gets <b>8500 requests</b> that takes <b>almost 2 hours</b> just for the lists.
>                     We also have to take <b>each profile and each contributor for the repository</b>.
>                     It takes time, <b>more than 2 hours</b> but the geting of data is not so much time consuming like the Github repository case. We also did a request for <i>"social graphs"</i>.
>                     It has just <b>787 repositories<b> so it does not include enough data.
